name: Build with Cabal

on:
  push:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.7', '9.0.2', '9.2', '9.4', '9.6']
        cabal: ['3.8']
        os: ['ubuntu-20.04', 'ubuntu-22.04', 'macOS-latest']

    steps:

    # Setup
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install GHC and Cabal
      uses: haskell/actions/setup@v2
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}
    - name: Confirm GHC and Cabal installation
      run: |
        ghc --version
        cabal --version
    - name: Configure project
      run: |
        cat > cabal.project.local <<EOF
        package ethereum
          documentation: False
          benchmarks: True
          tests: True
          extra-lib-dirs:
            /opt/local/lib
            /usr/local/opt/openssl/lib
          extra-include-dirs:
            /opt/local/include
            /usr/local/opt/openssl/include
        package hashes
          extra-lib-dirs:
            /opt/local/lib
            /usr/local/opt/openssl/lib
          extra-include-dirs:
            /opt/local/include
            /usr/local/opt/openssl/include
        EOF

    # Restore Packages from Caches
    - uses: actions/cache@v3
      name: Cache dist-newstyle
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}-1-cabal

    # Build
    - name: Update package database
      run: cabal update
    - name: Configure build
      run: |
        cabal build all --dry-run
        cabal freeze
    - name: Install build dependencies
      run: cabal build --only-dependencies
    - name: Build library
      run: cabal build

    # Tests
    - name: Run Tests
      run: cabal run ethereum-tests

    # benchmarks
    - name: Run Benchmarks
      if: "matrix.ghc != '9.2'"
      run: cabal bench
