name: Build with Cabal

on:
  push:
  schedule:
    - cron: '0 8 * * *'

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.8.4', '8.10.7', '9.0.1']
        cabal: ['3.4']
        os: ['ubuntu-18.04', 'ubuntu-20.04', 'macOS-latest']

    steps:

    # Setup
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install GHC and Cabal
      uses: haskell/actions/setup@v1.2.3
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}
    - name: Configure project
      run: |
        cat > cabal.project.local <<EOF
        package ethereum
          documentation: False
          benchmarks: True
          tests: True
        EOF

    # Restore Packages from Caches
    # - uses: actions/cache@v2.1.6
    - uses: pat-s/always-upload-cache@v2.1.5
      name: Cache dist-newstyle
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}-1-cabal

    # Build
    - name: Update package database
      run: cabal update
    - name: Configure build
      run: |
        cabal build all --dry-run
        cabal freeze
    - name: Install build dependencies
      run: cabal build --only-dependencies
    - name: Build library
      run: cabal build

    # Tests
    - name: Debug Run Tests
      run: |
        cabal run tests -- -p '/Ethhash.hash.prop_hash256/'
        cabal run tests -- -p '/Ethhash.hash.prop_hash512/'
        cabal run tests -- -p '/Ethhash.hash.prop_hashInPlace256/'
        cabal run tests -- -p '/Ethhash.hash.prop_hashInPlace512/'
        cabal run tests -- -p '/Ethhash.Cache.prop_cacheSize/'
        cabal run tests -- -p '/Ethhash.Cache.prop_dataSetSize/'
        cabal run tests -- -p '/Ethhash.Cache.seed/'
        cabal run tests -- -p '/Ethhash.Size Lookup Tables/'
        cabal run tests -- -p '/Ethhash.pow.powTest1/'
        cabal run tests -- -p '/Ethhash.pow.powTest2/'
        cabal run tests -- -p '/Ethhash.pow.block 22/'
        cabal run tests -- -p '/Ethhash.pow.block 30001/'
        cabal run tests -- -p '/Ethhash.pow.block 1/'
        cabal run tests -- -p '/Ethhash.DataSet/'
        cabal run tests -- -p '/Ethhash.Cache.cache bytes.1/'
        cabal run tests -- -p '/Ethhash.Cache.cache bytes.0/'
    - name: Run Tests
      run: cabal run ethereum-tests

    # benchmarks
    - name: Run Benchmarks
      run: cabal bench
